name: first_project
description: "A new Flutter project."
publish_to: 'none' #Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  objectbox_generator: any
  build_runner: ^2.4.8


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/android.png
    - assets/images/back.svg
